/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs102.program.serendipity.bookstore;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Subrina
 */
public class SerendipityFrame extends javax.swing.JFrame {

    private Reports report;
    private InventoryMenu inventory;

    /**
     * Creates new form SerendipityFrame
     */
    public SerendipityFrame() {
        initComponents();
        initializeStore();
    }

    public void initializeStore() {

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(0, 0, screenSize.width - 500, screenSize.height / 2);

        // center the jframe on screen
        this.setLocationRelativeTo(null);

        plReportMain.setVisible(false);
        plInventoryListing.setVisible(false);
        plInventoryMain.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnMainMenu = new javax.swing.ButtonGroup();
        rbtnReportMenu = new javax.swing.ButtonGroup();
        rbtnInventoryMenu = new javax.swing.ButtonGroup();
        plMain = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        plMainMenu = new javax.swing.JPanel();
        rbtnCashier = new javax.swing.JRadioButton();
        rbtnInventory = new javax.swing.JRadioButton();
        rbtnReport = new javax.swing.JRadioButton();
        btnExit = new javax.swing.JButton();
        plReportMain = new javax.swing.JPanel();
        plReportMenu = new javax.swing.JPanel();
        rbtnInvListing = new javax.swing.JRadioButton();
        rbtnInvWholesaleValue = new javax.swing.JRadioButton();
        rbtnInvRetailValue = new javax.swing.JRadioButton();
        rbtnListingByQuantity = new javax.swing.JRadioButton();
        rbtnListingByCost = new javax.swing.JRadioButton();
        rbtnListingByAge = new javax.swing.JRadioButton();
        rbtnReturnToMain = new javax.swing.JRadioButton();
        lblReportWelcome = new javax.swing.JLabel();
        btnExit1 = new javax.swing.JButton();
        plInventoryListing = new javax.swing.JPanel();
        lblInvListing = new javax.swing.JLabel();
        plInvListing = new javax.swing.JPanel();
        spInvListing = new javax.swing.JScrollPane();
        txtInvListing = new javax.swing.JTextArea();
        btnReportMenu = new javax.swing.JButton();
        plInventoryMain = new javax.swing.JPanel();
        lblInventoryWelcome = new javax.swing.JLabel();
        plInventoryMenu = new javax.swing.JPanel();
        rbtnLookUp = new javax.swing.JRadioButton();
        rbtnAdd = new javax.swing.JRadioButton();
        rbtnEdit = new javax.swing.JRadioButton();
        rbtnReturnToMain1 = new javax.swing.JRadioButton();
        btnExit2 = new javax.swing.JButton();
        plInventoryDatabase = new javax.swing.JPanel();
        lblInventoryDB = new javax.swing.JLabel();
        plInvListing1 = new javax.swing.JPanel();
        plMainMenu1 = new javax.swing.JPanel();
        rbtnCashier1 = new javax.swing.JRadioButton();
        rbtnInventory1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnReportMenu1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Serendipity Booksellers");

        plMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblWelcome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(153, 0, 0));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Serendipity Booksellers");
        lblWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        rbtnMainMenu.add(rbtnCashier);
        rbtnCashier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnCashier.setText("Cashier Module");
        rbtnCashier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        rbtnMainMenu.add(rbtnInventory);
        rbtnInventory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnInventory.setText("Inventory Database Module");
        rbtnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnInventoryActionPerformed(evt);
            }
        });

        rbtnMainMenu.add(rbtnReport);
        rbtnReport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnReport.setText("Report Module");
        rbtnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plMainMenuLayout = new javax.swing.GroupLayout(plMainMenu);
        plMainMenu.setLayout(plMainMenuLayout);
        plMainMenuLayout.setHorizontalGroup(
            plMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnCashier)
                    .addComponent(rbtnInventory)
                    .addComponent(rbtnReport))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        plMainMenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rbtnInventory, rbtnReport});

        plMainMenuLayout.setVerticalGroup(
            plMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnCashier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnInventory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnReport)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plMainLayout = new javax.swing.GroupLayout(plMain);
        plMain.setLayout(plMainLayout);
        plMainLayout.setHorizontalGroup(
            plMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plMainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit))
            .addGroup(plMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plMainLayout.createSequentialGroup()
                        .addComponent(plMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(plMainLayout.createSequentialGroup()
                        .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                        .addGap(67, 67, 67))))
        );
        plMainLayout.setVerticalGroup(
            plMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit))
        );

        plReportMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rbtnReportMenu.add(rbtnInvListing);
        rbtnInvListing.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnInvListing.setText("Inventory Listing");
        rbtnInvListing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnInvListingActionPerformed(evt);
            }
        });

        rbtnReportMenu.add(rbtnInvWholesaleValue);
        rbtnInvWholesaleValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnInvWholesaleValue.setText("Inventory Wholesale Value");
        rbtnInvWholesaleValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnInvWholesaleValueActionPerformed(evt);
            }
        });

        rbtnReportMenu.add(rbtnInvRetailValue);
        rbtnInvRetailValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnInvRetailValue.setText("Inventory Retail Value");
        rbtnInvRetailValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnInvRetailValueActionPerformed(evt);
            }
        });

        rbtnReportMenu.add(rbtnListingByQuantity);
        rbtnListingByQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnListingByQuantity.setText("Listing By Quantity");
        rbtnListingByQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnListingByQuantityActionPerformed(evt);
            }
        });

        rbtnReportMenu.add(rbtnListingByCost);
        rbtnListingByCost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnListingByCost.setText("Listing By Cost");
        rbtnListingByCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnListingByCostActionPerformed(evt);
            }
        });

        rbtnReportMenu.add(rbtnListingByAge);
        rbtnListingByAge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnListingByAge.setText("Listing By Age");
        rbtnListingByAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnListingByAgeActionPerformed(evt);
            }
        });

        rbtnReportMenu.add(rbtnReturnToMain);
        rbtnReturnToMain.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnReturnToMain.setText("Return to the Main Menu");
        rbtnReturnToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnReturnToMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plReportMenuLayout = new javax.swing.GroupLayout(plReportMenu);
        plReportMenu.setLayout(plReportMenuLayout);
        plReportMenuLayout.setHorizontalGroup(
            plReportMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plReportMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plReportMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnInvListing, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbtnInvWholesaleValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(rbtnInvRetailValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbtnListingByQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbtnListingByCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbtnListingByAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbtnReturnToMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(479, 479, 479))
        );
        plReportMenuLayout.setVerticalGroup(
            plReportMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plReportMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnInvListing, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnInvWholesaleValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(rbtnInvRetailValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnListingByQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnListingByCost, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnListingByAge, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(rbtnReturnToMain, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        plReportMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rbtnInvListing, rbtnInvRetailValue, rbtnInvWholesaleValue, rbtnListingByAge, rbtnListingByCost, rbtnListingByQuantity, rbtnReturnToMain});

        lblReportWelcome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblReportWelcome.setForeground(new java.awt.Color(153, 0, 0));
        lblReportWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportWelcome.setText("Serendipity Booksellers - Report Menu");

        btnExit1.setText("Exit");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plReportMainLayout = new javax.swing.GroupLayout(plReportMain);
        plReportMain.setLayout(plReportMainLayout);
        plReportMainLayout.setHorizontalGroup(
            plReportMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plReportMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(plReportMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReportWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plReportMainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit1))
        );
        plReportMainLayout.setVerticalGroup(
            plReportMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plReportMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReportWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plReportMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit1))
        );

        plInventoryListing.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblInvListing.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInvListing.setForeground(new java.awt.Color(153, 0, 0));
        lblInvListing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInvListing.setText("Serendipity Booksellers - Inventory Listing");
        lblInvListing.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtInvListing.setEditable(false);
        txtInvListing.setColumns(20);
        txtInvListing.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtInvListing.setLineWrap(true);
        txtInvListing.setRows(5);
        spInvListing.setViewportView(txtInvListing);

        btnReportMenu.setText("Return to Menu");
        btnReportMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plInvListingLayout = new javax.swing.GroupLayout(plInvListing);
        plInvListing.setLayout(plInvListingLayout);
        plInvListingLayout.setHorizontalGroup(
            plInvListingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plInvListingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plInvListingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spInvListing)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plInvListingLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReportMenu)))
                .addContainerGap())
        );
        plInvListingLayout.setVerticalGroup(
            plInvListingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plInvListingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spInvListing, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportMenu)
                .addContainerGap())
        );

        javax.swing.GroupLayout plInventoryListingLayout = new javax.swing.GroupLayout(plInventoryListing);
        plInventoryListing.setLayout(plInventoryListingLayout);
        plInventoryListingLayout.setHorizontalGroup(
            plInventoryListingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plInventoryListingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInvListing, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(plInvListing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        plInventoryListingLayout.setVerticalGroup(
            plInventoryListingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plInventoryListingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInvListing, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plInvListing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        plInventoryMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblInventoryWelcome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInventoryWelcome.setForeground(new java.awt.Color(153, 0, 0));
        lblInventoryWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInventoryWelcome.setText("Serendipity Booksellers - Inventory Database");
        lblInventoryWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        rbtnInventoryMenu.add(rbtnLookUp);
        rbtnLookUp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnLookUp.setText("Look Up a Book");
        rbtnLookUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbtnLookUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnLookUpActionPerformed(evt);
            }
        });

        rbtnInventoryMenu.add(rbtnAdd);
        rbtnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnAdd.setText("Add a Book");
        rbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAddActionPerformed(evt);
            }
        });

        rbtnInventoryMenu.add(rbtnEdit);
        rbtnEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnEdit.setText("Edit Book");
        rbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEditActionPerformed(evt);
            }
        });

        rbtnInventoryMenu.add(rbtnReturnToMain1);
        rbtnReturnToMain1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnReturnToMain1.setText("Return to the Main Menu");
        rbtnReturnToMain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnReturnToMain1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plInventoryMenuLayout = new javax.swing.GroupLayout(plInventoryMenu);
        plInventoryMenu.setLayout(plInventoryMenuLayout);
        plInventoryMenuLayout.setHorizontalGroup(
            plInventoryMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plInventoryMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plInventoryMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plInventoryMenuLayout.createSequentialGroup()
                        .addGroup(plInventoryMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnLookUp)
                            .addComponent(rbtnAdd)
                            .addComponent(rbtnEdit))
                        .addGap(0, 537, Short.MAX_VALUE))
                    .addComponent(rbtnReturnToMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        plInventoryMenuLayout.setVerticalGroup(
            plInventoryMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plInventoryMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnLookUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnReturnToMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        btnExit2.setText("Exit");
        btnExit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plInventoryMainLayout = new javax.swing.GroupLayout(plInventoryMain);
        plInventoryMain.setLayout(plInventoryMainLayout);
        plInventoryMainLayout.setHorizontalGroup(
            plInventoryMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plInventoryMainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plInventoryMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plInventoryMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInventoryWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plInventoryMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        plInventoryMainLayout.setVerticalGroup(
            plInventoryMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plInventoryMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInventoryWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plInventoryMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit2))
        );

        plInventoryDatabase.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblInventoryDB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInventoryDB.setForeground(new java.awt.Color(153, 0, 0));
        lblInventoryDB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInventoryDB.setText("Serendipity Booksellers - Inventory Database");
        lblInventoryDB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        rbtnMainMenu.add(rbtnCashier1);
        rbtnCashier1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnCashier1.setText("Find By Title");
        rbtnCashier1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        rbtnMainMenu.add(rbtnInventory1);
        rbtnInventory1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnInventory1.setText("Find by ISBN");
        rbtnInventory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnInventory1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plMainMenu1Layout = new javax.swing.GroupLayout(plMainMenu1);
        plMainMenu1.setLayout(plMainMenu1Layout);
        plMainMenu1Layout.setHorizontalGroup(
            plMainMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plMainMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plMainMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnCashier1)
                    .addComponent(rbtnInventory1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plMainMenu1Layout.setVerticalGroup(
            plMainMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plMainMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnCashier1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnInventory1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnReportMenu1.setText("Return to Menu");
        btnReportMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportMenu1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Value");

        jButton1.setText("Search");

        javax.swing.GroupLayout plInvListing1Layout = new javax.swing.GroupLayout(plInvListing1);
        plInvListing1.setLayout(plInvListing1Layout);
        plInvListing1Layout.setHorizontalGroup(
            plInvListing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plInvListing1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnReportMenu1))
            .addGroup(plInvListing1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plInvListing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plMainMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(plInvListing1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        plInvListing1Layout.setVerticalGroup(
            plInvListing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plInvListing1Layout.createSequentialGroup()
                .addComponent(plMainMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plInvListing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnReportMenu1))
        );

        javax.swing.GroupLayout plInventoryDatabaseLayout = new javax.swing.GroupLayout(plInventoryDatabase);
        plInventoryDatabase.setLayout(plInventoryDatabaseLayout);
        plInventoryDatabaseLayout.setHorizontalGroup(
            plInventoryDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plInventoryDatabaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plInventoryDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInventoryDB, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                    .addComponent(plInvListing1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        plInventoryDatabaseLayout.setVerticalGroup(
            plInventoryDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plInventoryDatabaseLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblInventoryDB, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(plInvListing1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(plReportMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(plInventoryListing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(plInventoryMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(plInventoryDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(plReportMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(plInventoryListing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(plInventoryMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(plInventoryDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnInventoryActionPerformed
        plMain.setVisible(false);
        plInventoryMain.setVisible(true);
        rbtnMainMenu.clearSelection();

        inventory = new InventoryMenu();
    }//GEN-LAST:event_rbtnInventoryActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        JOptionPane.showMessageDialog(this, "Thank You For Shopping at Serendipity!", "Serendipity Booksellers", JOptionPane.PLAIN_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void rbtnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnReportActionPerformed
        plMain.setVisible(false);
        plReportMain.setVisible(true);
        rbtnMainMenu.clearSelection();

        report = new Reports();
    }//GEN-LAST:event_rbtnReportActionPerformed

    private void rbtnListingByAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnListingByAgeActionPerformed
        report.setSortType(Reports.SORT_TYPES.AGE);
        plReportMain.setVisible(false);
        plInventoryListing.setVisible(true);
        rbtnReportMenu.clearSelection();
        report.sortBooks();
        lblInvListing.setText("Serendipity Booksellers - Listing by Age");
        txtInvListing.setText(report.getAllBooks());
    }//GEN-LAST:event_rbtnListingByAgeActionPerformed

    private void rbtnReturnToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnReturnToMainActionPerformed
        plMain.setVisible(true);
        plReportMain.setVisible(false);
        plInventoryListing.setVisible(false);
        rbtnReportMenu.clearSelection();
    }//GEN-LAST:event_rbtnReturnToMainActionPerformed

    private void rbtnInvListingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnInvListingActionPerformed
        report.setSelection(Reports.MENU_OPTIONS.INVENTORY_LISTING.ordinal());
        plReportMain.setVisible(false);
        plInventoryListing.setVisible(true);
        rbtnReportMenu.clearSelection();
        txtInvListing.setText(report.getAllBooks());
    }//GEN-LAST:event_rbtnInvListingActionPerformed

    private void btnReportMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportMenuActionPerformed
        plReportMain.setVisible(true);
        plInventoryListing.setVisible(false);
//        lblInvListing.setText("Serendipity Booksellers - Inventory");
    }//GEN-LAST:event_btnReportMenuActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        btnExitActionPerformed(evt);
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void rbtnInvWholesaleValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnInvWholesaleValueActionPerformed
//        report.setSelection(Reports.MENU_OPTIONS.INVENTORY_LISTING.ordinal());
        plReportMain.setVisible(false);
        plInventoryListing.setVisible(true);
        rbtnReportMenu.clearSelection();
        report.listByWholesaleValue();
        lblInvListing.setText("Serendipity Booksellers - Listing by Wholesale Value");
        txtInvListing.setText(report.getAllBooks());
    }//GEN-LAST:event_rbtnInvWholesaleValueActionPerformed

    private void rbtnInvRetailValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnInvRetailValueActionPerformed
        plReportMain.setVisible(false);
        plInventoryListing.setVisible(true);
        rbtnReportMenu.clearSelection();
        report.listByWholesaleValue();
        lblInvListing.setText("Serendipity Booksellers - Listing by Retail Value");
        txtInvListing.setText(report.getAllBooks());

    }//GEN-LAST:event_rbtnInvRetailValueActionPerformed

    private void rbtnListingByQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnListingByQuantityActionPerformed
        report.setSortType(Reports.SORT_TYPES.QUANTITY);
        plReportMain.setVisible(false);
        plInventoryListing.setVisible(true);
        rbtnReportMenu.clearSelection();
        report.sortBooks();
        lblInvListing.setText("Serendipity Booksellers - Listing by Quantity");
        txtInvListing.setText(report.getAllBooks());
    }//GEN-LAST:event_rbtnListingByQuantityActionPerformed

    private void rbtnListingByCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnListingByCostActionPerformed
        report.setSortType(Reports.SORT_TYPES.COST);
        plReportMain.setVisible(false);
        plInventoryListing.setVisible(true);
        rbtnReportMenu.clearSelection();
        report.sortBooks();
        lblInvListing.setText("Serendipity Booksellers - Listing by Cost");
        txtInvListing.setText(report.getAllBooks());
    }//GEN-LAST:event_rbtnListingByCostActionPerformed

    private void rbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAddActionPerformed

    private void rbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnEditActionPerformed

    private void btnExit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit2ActionPerformed
        btnExitActionPerformed(evt);
    }//GEN-LAST:event_btnExit2ActionPerformed

    private void rbtnLookUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnLookUpActionPerformed
//        inventory.lookupBook();
        plInventoryDatabase.setVisible(true);
        plInventoryMain.setVisible(false);
        rbtnInventoryMenu.clearSelection();
    }//GEN-LAST:event_rbtnLookUpActionPerformed

    private void rbtnReturnToMain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnReturnToMain1ActionPerformed
        plMain.setVisible(true);
        plReportMain.setVisible(false);
        plInventoryListing.setVisible(false);
        plInventoryMain.setVisible(false);
        rbtnInventoryMenu.clearSelection();
        rbtnReportMenu.clearSelection();
    }//GEN-LAST:event_rbtnReturnToMain1ActionPerformed

    private void btnReportMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportMenu1ActionPerformed
        btnReportMenuActionPerformed(evt);
    }//GEN-LAST:event_btnReportMenu1ActionPerformed

    private void rbtnInventory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnInventory1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnInventory1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SerendipityFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SerendipityFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SerendipityFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SerendipityFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SerendipityFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnExit2;
    private javax.swing.JButton btnReportMenu;
    private javax.swing.JButton btnReportMenu1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblInvListing;
    private javax.swing.JLabel lblInventoryDB;
    private javax.swing.JLabel lblInventoryWelcome;
    private javax.swing.JLabel lblReportWelcome;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel plInvListing;
    private javax.swing.JPanel plInvListing1;
    private javax.swing.JPanel plInventoryDatabase;
    private javax.swing.JPanel plInventoryListing;
    private javax.swing.JPanel plInventoryMain;
    private javax.swing.JPanel plInventoryMenu;
    private javax.swing.JPanel plMain;
    private javax.swing.JPanel plMainMenu;
    private javax.swing.JPanel plMainMenu1;
    private javax.swing.JPanel plReportMain;
    private javax.swing.JPanel plReportMenu;
    private javax.swing.JRadioButton rbtnAdd;
    private javax.swing.JRadioButton rbtnCashier;
    private javax.swing.JRadioButton rbtnCashier1;
    private javax.swing.JRadioButton rbtnEdit;
    private javax.swing.JRadioButton rbtnInvListing;
    private javax.swing.JRadioButton rbtnInvRetailValue;
    private javax.swing.JRadioButton rbtnInvWholesaleValue;
    private javax.swing.JRadioButton rbtnInventory;
    private javax.swing.JRadioButton rbtnInventory1;
    private javax.swing.ButtonGroup rbtnInventoryMenu;
    private javax.swing.JRadioButton rbtnListingByAge;
    private javax.swing.JRadioButton rbtnListingByCost;
    private javax.swing.JRadioButton rbtnListingByQuantity;
    private javax.swing.JRadioButton rbtnLookUp;
    private javax.swing.ButtonGroup rbtnMainMenu;
    private javax.swing.JRadioButton rbtnReport;
    private javax.swing.ButtonGroup rbtnReportMenu;
    private javax.swing.JRadioButton rbtnReturnToMain;
    private javax.swing.JRadioButton rbtnReturnToMain1;
    private javax.swing.JScrollPane spInvListing;
    private javax.swing.JTextArea txtInvListing;
    // End of variables declaration//GEN-END:variables
}
